teams = {
    "Palmeiras": "Palmeiras",
    "Santos": "Santos",
    "Cruzeiro": "Cruzeiro",
    "Botafogo": "Botafogo RJ",
    "Grêmio": "Gremio",
    "Fluminense": "Fluminense",
    "São Paulo": "Sao Paulo",
    "Atlético Mineiro": "Atletico-MG",
    "Atlético PR": "Atletico-PR",
    "Corinthians": "Corinthians",
    "Vasco da Gama": "Vasco",
    "Bahia": "Bahia",
    "Coritiba": "Coritiba",
    "Internacional": "Internacional",
    "América Mineiro": "America MG",
    "Bragantino": "Bragantino",
    "Goiás": "Goias",
    "Cuiabá": "Cuiaba",
    "Fortaleza": "Fortaleza",
    "Flamengo": "Flamengo RJ",
    "Arsenal": "Arsenal",
    "Tottenham Hotspur": "Tottenham",
    "Manchester City": "Man City",
    "Crystal Palace": "Crystal Palace",
    "Everton": "Everton",
    "Burnley": "Burnley",
    "AFC Bournemouth": "Bournemouth",
    "Manchester United": "Man United",
    "Liverpool": "Liverpool",
    "Chelsea": "Chelsea",
    "West Ham United": "West Ham",
    "Newcastle United": "Newcastle",
    "Aston Villa": "Aston Villa",
    "Fulham": "Fulham",
    "Brighton & Hove Albion": "Brighton",
    "Nottingham Forest": "Nott'm Forest",
    "Brentford": "Brentford",
    "Wolverhampton Wanderers": "Wolves",
    "Sheffield United": "Sheffield United",
    "Luton Town": "Luton"
}
